apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: playground
spec:
  type: NodePort
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30001
